apiVersion: v1
kind: Service
metadata:
  name: appscode-ossec-server
  namespace: kube-system
  labels:
    k8s-app: appscode-ossec-server
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "OssecServer"
spec:
  ports:
  - name: ossec
    port: 1514
    protocol: UDP
  - name: https
    port: 55000
    protocol: TCP
  selector:
    k8s-app: appscode-ossec-server
