apiVersion: v1
kind: ReplicationController
metadata:
  name: appscode-ossec-server-1.1.0
  namespace: kube-system
  labels:
    k8s-app: appscode-ossec-server
    version: '1.1.0'
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: appscode-ossec-server
    version: '1.1.0'
  template:
    metadata:
      labels:
        k8s-app: appscode-ossec-server
        version: '1.1.0'
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: ossec-server
        image: appscode/ossec-wazuh-server:1.1.0
        resources:
          limits:
            cpu: 100m
        ports:
        - name: ossec
          containerPort: 1514
          protocol: UDP
        - name: https
          containerPort: 55000
          protocol: TCP
        volumeMounts:
        - name: ossec-api-secrets
          mountPath: /var/ossec/api/ssl
          readOnly: true
        - name: ossec-server-data
          mountPath: /var/ossec/data
        - name: log
          mountPath: /log
          readOnly: true
      volumes:
      - name: ossec-api-secrets
        secret:
          secretName: appscode-ossec
      - name: ossec-server-data
        emptyDir: {}
      - name: log
        hostPath:
          path: /var/log/
